version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_music
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: antoaneta
      POSTGRES_PASSWORD: 211081
      POSTGRES_DB: music
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
